### ISSUE TITLE
Code requires baidu_site, yahoo_domain recon-ng modules which are no longer part of LaNMaSteR53/recon-ng

### ISSUE THREAD

**Issue by ldionmarcil** [jhaddix/domain#10]
https://github.com/jhaddix/domain/blob/master/enumall.py#L45

`enumall.py` tries to load `recon/domains-hosts/{baidu_site,yahoo_domain}` which have been removed from [LaNMaSteR53/recon-ng](https://bitbucket.org/LaNMaSteR53/recon-ng/) since April 22, 2016, [commit d23da13](https://bitbucket.org/LaNMaSteR53/recon-ng/commits/d23da13f2b6d6b4f98ffc11ef027435056a5075c?at=master).

I suggest removing the modules from the list, or suggesting a different, more specific fork of recon-ng which contains the baidu & yahoo plugins.

**Comment by jhaddix** [comment]
i saw this too, working on a rewrite for these modules atm. Stay tuned.

**Comment by jhaddix** [comment]
removed them for now
